# Generated by Django 4.0.4 on 2022-05-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('categories', models.CharField(choices=[('FS', 'Full Stack'), ('FE', 'Front End'), ('Be', 'Back End')], max_length=50)),
                ('status', models.CharField(choices=[('FS', 'Full Stack'), ('FE', 'Front End'), ('Be', 'Back End')], max_length=50)),
            ],
        ),
    ]
